export const ADD_BOOK = 'ADD_BOOK';
// export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
// export const ADD_BOOK_ERROR = 'ADD_BOOK_ERROR'; 

export const DELETE_BOOK = 'DELETE_BOOK';
// export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
// export const DELETE_BOOK_ERROR = 'DELETE_BOOK_ERROR';

export const UPDATE_BOOK = 'UPDATE_BOOK';
// export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
// export const UPDATE_BOOK_ERROR = 'UPDATE_BOOK_ERROR';

export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
// export const CHANGE_SORT_ORDER_SUCCESS = 'CHANGE_SORT_ORDER_SUCCESS';
// export const CHANGE_SORT_ORDER_ERROR = 'CHANGE_SORT_ORDER_ERROR';